package app

const (
	PermClientsRead      = "clients:read"
	PermClientsWrite     = "clients:write"
	PermClientsDelete    = "clients:delete"
	PermDocumentsRead    = "documents:read"
	PermDocumentsWrite   = "documents:write"
	PermDocumentsDelete  = "documents:delete"
	PermContractsRead    = "contracts:read"
	PermContractsWrite   = "contracts:write"
	PermContractsDelete  = "contracts:delete"
	PermNotesRead        = "workspace_notes:read"
	PermNotesWrite       = "workspace_notes:write"
	PermNotesDelete      = "workspace_notes:delete"
	PermTicketingRead    = "ticketing:read"
	PermTicketingWrite   = "ticketing:write"
	PermTicketingDelete  = "ticketing:delete"
	PermChatRead         = "chat:read"
	PermChatWrite        = "chat:write"
	PermTemplatesRead    = "message_templates:read"
	PermTemplatesWrite   = "message_templates:write"
	PermTemplatesDelete  = "message_templates:delete"
	PermHRRead           = "hr:read"
	PermHRWrite          = "hr:write"
	PermPlannerRead      = "planner:read"
	PermPlannerWrite     = "planner:write"
	PermPlannerDelete    = "planner:delete"
	PermAutomationRead   = "automation_rules:read"
	PermAutomationWrite  = "automation_rules:write"
	PermAutomationDelete = "automation_rules:delete"
	PermReportsRead      = "reports:read"
	PermActivityRead     = "activity_log:read"
	PermMembersRead      = "members:read"
	PermMembersWrite     = "members:write"
	PermMembersDelete    = "members:delete"
	PermRolesRead        = "roles:read"
	PermRolesWrite       = "roles:write"
	PermCategoriesRead   = "employee_categories:read"
	PermCategoriesWrite  = "employee_categories:write"
	PermCategoriesDelete = "employee_categories:delete"
)
