package app

const (
	PermClientsRead      = "clients:read"
	PermClientsWrite     = "clients:write"
	PermClientsDelete    = "clients:delete"
	PermDocumentsRead    = "documents:read"
	PermDocumentsWrite   = "documents:write"
	PermDocumentsDelete  = "documents:delete"
	PermContractsRead    = "contracts:read"
	PermContractsWrite   = "contracts:write"
	PermContractsDelete  = "contracts:delete"
	PermNotesRead        = "workspace_notes:read"
	PermNotesWrite       = "workspace_notes:write"
	PermNotesDelete      = "workspace_notes:delete"
	PermTicketingRead    = "ticketing:read"
	PermTicketingWrite   = "ticketing:write"
	PermTicketingDelete  = "ticketing:delete"
	PermMembersRead      = "members:read"
	PermMembersWrite     = "members:write"
	PermMembersDelete    = "members:delete"
	PermRolesRead        = "roles:read"
	PermRolesWrite       = "roles:write"
	PermCategoriesRead   = "employee_categories:read"
	PermCategoriesWrite  = "employee_categories:write"
	PermCategoriesDelete = "employee_categories:delete"
)
